/* THIS FILE WAS GENERATED!
 *
 * This file was generated. You may or may not want to
 * edit it directly.
 */

#include QMK_KEYBOARD_H
#include "keycodes.h"
#include "g/keymap_combo.h"


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
       [_BASE] = LAYOUT_split_3x5_2(KC_J,KC_G,KC_H,KC_P,KC_V,KC_BSLS,DOT,SLASH,QUOTE,MINS,KC_R,LT(_FUN, KC_S),KC_N,LT(_SYM, KC_T),KC_B,COMM,LT(_SYM, KC_A),KC_E,LT(_NUMBLOCK, KC_I),KC_C,KC_X,KC_F,LALT_T(KC_M),LGUI_T(KC_D),KC_K,KC_Z,RGUI_T(KC_U),RALT_T(KC_O),KC_Y,KC_W,NAV_SPC,OS_LSFT,OS_LCTL,LSFT_T(KC_L)),
   [_NAV] = LAYOUT_split_3x5_2(SW_APP,G(KC_GRV),BACK,FWD,KC_NO,KC_NO,TAB_L,KC_UP,TAB_R,KC_RPRN,OS_LSFT,OS_LCTL,OS_LALT,OS_LGUI,OSM(MOD_MEH),KC_NO,KC_LEFT,KC_DOWN,KC_RIGHT,KC_RGHT,KC_NO,SPACE_L,KC_NO,SPACE_R,KC_NO,KC_NO,KC_LBRC,KC_RBRC,KC_GT,LLOCK,KC_NO,KC_NO,OS_LCTL,KC_SPACE),
   [_SYM] = LAYOUT_split_3x5_2(KC_AT,KC_UNDS,KC_LBRC,KC_RBRC,KC_CIRC,KC_EXLM,KC_LT,KC_GT,KC_EQL,KC_AMPR,KC_BSLS,KC_SLSH,KC_LCBR,KC_RCBR,KC_ASTR,KC_QUES,KC_LPRN,KC_RPRN,KC_MINS,KC_COLN,KC_HASH,KC_DLR,KC_PIPE,KC_TILD,KC_GRV,KC_PLUS,KC_PERC,KC_QUOT,KC_DQUO,KC_SCLN,NAV_SPC,OS_LSFT,OS_LCTL,KC_RGUI),
   [_NUM] = LAYOUT_split_3x5_2(KC_J,NUM_G,KC_NO,KC_P,KC_TRNS,KC_BSLS,KC_COMM,KC_DOT,KC_MINS,KC_SLSH,LSFT_T(KC_7),LCTL_T(KC_5),LALT_T(KC_3),LGUI_T(KC_1),NUM_G,KC_SLSH,LGUI_T(KC_2),LALT_T(KC_4),LCTL_T(KC_6),LSFT_T(KC_8),SLASH,KC_X,KC_TRNS,KC_9,KC_TRNS,KC_P,KC_0,KC_O,KC_K,KC_J,NAV_SPC,KC_K,KC_NO,KC_NO),
   [_NUMBLOCK] = LAYOUT_split_3x5_2(KC_LBRC,KC_7,KC_8,KC_9,KC_RBRC,KC_BSLS,COMM,DOT,KC_RCTL,KC_NO,KC_SCLN,KC_1,KC_2,KC_3,KC_MINS,A(S(KC_2)),KC_LT,KC_GT,KC_NO,KC_LSFT,SLASH,KC_4,KC_5,KC_6,KC_EQL,KC_NO,KC_RGUI,KC_RALT,KC_NO,LLOCK,KC_0,OS_LSFT,OS_LCTL,LSFT_T(KC_SPC)),
   [_FUN] = LAYOUT_split_3x5_2(KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_F11,KC_F12,KC_NO,KC_NO,KC_NO,KC_LSFT,KC_NO,KC_LALT,KC_LGUI,KC_NO,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_F6,KC_F7,KC_F8,KC_F9,KC_F10,NAV_SPC,OSM(MOD_LSFT),OSM(MOD_RCTL),KC_LSFT),
   [_MODS] = LAYOUT_split_3x5_2(KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,OS_LGUI,OS_LALT,OS_LCTL,OS_LSFT,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,OSM(MOD_RALT),KC_NO,KC_NO,TO(0),OSM(MOD_LSFT),OSM(MOD_RCTL),TO(_NUM))
};
#include "combos_terms.inc"
