/* THIS FILE WAS GENERATED!
 *
 * This file was generated. You may or may not want to
 * edit it directly.
 */

#include QMK_KEYBOARD_H
#include "keycodes.h"
#include "g/keymap_combo.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
       [_BASE] = LAYOUT_split_3x5_2(KC_J,KC_G,KC_H,KC_P,KC_V,KC_BSLS,DOT,SLASH,QUOTE,TILD,___R___,___S___,KC_N,___T___,KC_B,COMM,___A___,KC_E,___I___,___C___,KC_X,KC_F,___M___,___D___,KC_K,KC_Z,___U___,___O___,KC_Y,KC_W,_SPACE_,OS_LSFT,OS_LCTL,___L___),
   [_NAV] = LAYOUT_split_3x5_2(SW_APP,G(KC_GRV),BACK,FWD,KC_NO,KC_NO,TAB_L,KC_UP,TAB_R,KC_RPRN,OS_LSFT,OS_LCTL,OS_LALT,OS_LGUI,OSM(MOD_MEH),KC_NO,KC_LEFT,KC_DOWN,KC_RIGHT,KC_RGHT,KC_NO,SPACE_L,KC_NO,SPACE_R,KC_NO,KC_NO,KC_LBRC,KC_RBRC,KC_GT,LLOCK,NAV_SPC,OS_LSFT,OS_LCTL,KC_RGUI),
   [_NUM] = LAYOUT_split_3x5_2(KC_J,NUM_G,KC_NO,KC_P,KC_TRNS,KC_BSLS,KC_COMM,KC_DOT,KC_MINS,KC_SLSH,LSFT_T(KC_7),LCTL_T(KC_5),LALT_T(KC_3),LGUI_T(KC_1),NUM_G,KC_SLSH,LGUI_T(KC_2),LALT_T(KC_4),LCTL_T(KC_6),LSFT_T(KC_8),SLASH,KC_X,KC_TRNS,KC_9,KC_TRNS,KC_P,KC_0,KC_O,KC_K,KC_J,NAV_SPC,KC_K,KC_NO,KC_NO),
   [_SYM] = LAYOUT_split_3x5_2(KC_GRV,KC_LT,KC_ASTR,KC_GT,KC_NO,KC_QUES,KC_LBRC,KC_UNDS,KC_MINS,KC_RBRC,KC_BSLS,KC_LPRN,KC_PIPE,KC_HASH,KC_RPRN,KC_EXLM,KC_LCBR,KC_TILD,KC_SLSH,KC_RCBR,KC_AT,KC_EQL,KC_AMPR,KC_PLUS,KC_NO,KC_NO,KC_DLR,KC_CIRC,KC_PERC,KC_NO,NAV_SPC,OS_LSFT,OS_LCTL,KC_RGUI)
};
#include "combos_terms.inc"
