/* THIS FILE WAS GENERATED!
 *
 * This file was generated. You may or may not want to
 * edit it directly.
 */

#include QMK_KEYBOARD_H
#include "keycodes.h"
#include "g/keymap_combo.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
       [_ALPHA1] = LAYOUT_split_3x5_2(KC_COMM,KC_L,KC_G,KC_D,KC_T,KC_DOT,KC_H,KC_U,KC_O,KC_BSPC,KC_I,KC_S,KC_R,KC_T,OS_LSFT,OS_LSFT,KC_N,KC_E,KC_A,KC_C,KC_1,KC_V,OS_LCTL,OS_LSFT,KC_F18,KC_F19,OS_LSFT,OS_LCTL,KC_QUOT,KC_0,MEH_T(KC_SPC),KC_BSPC,REPEAT,OSL(_ALPHA2)),
   [_ALPHA2] = LAYOUT_split_3x5_2(KC_NO,KC_V,KC_W,KC_M,KC_NO,KC_NO,KC_F,KC_QUOT,KC_Z,KC_NO,KC_Q,KC_J,KC_P,KC_K,OS_LSFT,OS_LSFT,KC_B,KC_DOT,KC_X,KC_Y,KC_1,KC_W,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,S(KC_QUOT),KC_NO,OS_LSFT,KC_BSPC,OSL(_ALPHA2_UPPER),TO_ALPHA2_UPPER),
   [_ALPHA2_UPPER] = LAYOUT_split_3x5_2(KC_NO,S(KC_V),S(KC_W),S(KC_M),KC_NO,KC_NO,S(KC_F),S(KC_QUOT),S(KC_Z),KC_NO,S(KC_Q),S(KC_J),S(KC_P),S(KC_K),OS_LSFT,OS_LSFT,S(KC_B),KC_COMM,S(KC_X),S(KC_Y),KC_NO,S(KC_W),KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,OS_LSFT,KC_BSPC,KC_BSPC,TO_ALPHA2_UPPER),
   [_NUM] = LAYOUT_split_3x5_2(KC_LBRC,KC_7,KC_8,KC_9,KC_RBRC,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_SCLN,KC_4,KC_5,KC_6,KC_EQL,OSM(MOD_MEH),OSM(MOD_RGUI),OSM(MOD_RALT),OSM(MOD_RCTL),OSM(MOD_RSFT),KC_GRV,KC_1,KC_2,KC_3,KC_MINS,KC_NO,KC_NO,KC_NO,KC_BSLS,KC_SLSH,KC_0,OSM(MOD_LSFT),OSM(MOD_LCTL),OSL(_FUN)),
   [_FUN] = LAYOUT_split_3x5_2(KC_NO,KC_F7,KC_F8,KC_F9,KC_F10,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_F4,KC_F5,KC_F6,KC_F11,OSM(MOD_MEH),OSM(MOD_RGUI),OSM(MOD_RALT),OSM(MOD_RCTL),OSM(MOD_RSFT),KC_NO,KC_F1,KC_F2,KC_F3,KC_F12,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,LT(1,KC_SPC),OSM(MOD_LSFT),OSM(MOD_LCTL),OSL(_FUN))
};
#include "combos_terms.inc"
